import Head from 'next/head'
import Navbar2 from '../components/Navbar2'
import HeroSection from '../components/HeroSection'
import TopCoupons from '../components/TopCoupons'
import InfoSection from '../components/InfoSection'
import TopCategories from '../components/TopCategories'
import PromoSection from '../components/PromoSection'
import Footer from '../components/Footer'
import Brand from '../models/Brand'
import Coupon from '../models/Coupon'
import mongoose from 'mongoose'

function Home({ brands, coupons }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar2 />
        <HeroSection brands={brands} />
        <TopCoupons coupons={coupons} />
        <InfoSection />
        <TopCategories />
        <PromoSection brands={brands} />
        <Footer />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGO_URI)
  }
  let brands = await Brand.find().limit(7);
  let coupons = await Coupon.find().limit(12);
  return {
    props: {
      brands: JSON.parse(JSON.stringify(brands)),
      coupons: JSON.parse(JSON.stringify(coupons)),
    },
  }
}

export default Home
