const mongoose = require('mongoose');

const BrandsInfosSchema = new mongoose.Schema({
  mid: { type: Number, required: true },
  merchantname: { type: String, required: true },
  content: { type: String, required: true },
  blog: { type: String },
  facebook: { type: String },
  instagram: { type: String },
  twitter: { type: String },
  youtube: { type: String },
  pinterest: { type: String },
  tiktok: { type: String },
  tumbler: { type: String },
  linkedin: { type: String },
  snapchat: { type: String },
  sale: { type: String },
  womensale: { type: String },
  mensale: { type: String },
  boysale: { type: String },
  girlsale: { type: String },
  clearance: { type: String },
  menclearance: { type: String },
  womenclearance: { type: String },
  girlsclearance: { type: String },
  boysclearance: { type: String },
  freeshipping: { type: String },
  coupon: { type: String },
  studentdiscount: { type: String },
  militarydiscount: { type: String },
  teacherdiscount: { type: String },
  firstresponders: { type: String },
  doctorsandnursesdiscount: { type: String },
  corporatediscount: { type: String },
  youthdiscount: { type: String },
  employeediscount: { type: String },
  aaadiscount: { type: String },
  retireediscounts: { type: String },
  storelocator: { type: String },
  returnpolicy: { type: String },
  shippingpolicy: { type: String },
  mobileappandroid: { type: String },
  mobileappiphone: { type: String },
  rewardanchortext1: { type: String },
  rewardurl1: { type: String },
  rewardanchortext2: { type: String },
  rewardurl2: { type: String },
  referfriend: { type: String },
  googleplus: { type: String },
  address: { type: String },
  email: { type: String },
  phone: { type: String },
}, { timestamps: true });

mongoose.models = {}
export default mongoose.model("BrandsInfos", BrandsInfosSchema);